sudo: required

language: go

go:
  - 1.3

addons:
  postgresql: "9.3"

env:
  global:
    - ORACLE_FILE=oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    - ORACLE_INSTANTCLIENT_FILE=oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
    - ORACLE_INSTANTCLIENT_SDK_FILE=oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm
    - PKG_CONFIG_PATH="$TRAVIS_BUILD_DIR/.travis/oracle-instantclient"
    - secure: MYJoJzE5nf+w3Q+gCUskA9NyRyEMdVRvtWmqyGKDt7tdaJzPmvCZaHZ5vsgyQJNxuW8ldMbNgslJsdaMPMDzMIpYC1uWXjk5w7W9HqmIOyvja7IPz2ATXn0c9BEcs4vnjggFIezoEw+DUMJYlfx21C+KpUFOoBg5gGXHOvpwWHAQI8HmNzhbQ9jF9ymgcRe4Q0erVnusa67EpbGFHAdTcqlkJD4UI5p84Q1Bv8mV87gUH0+WPacXdpWBjGWl2E+kA82kWf4kzme+BGru25Yw0p8wE/Pu9lspwsijamUjzBHlUQhxnrLw24C0Ug6RFQx4HBCiAKPCqx6pIUm2JTwaeq9RdCwVpV0Yt8Pe5ukL+zcf0VjsiKj0s9JGL8Gmp1E+HdzJKz9AHyD/rk/FvJoiJrpSZJEIdT4KI5hbmNBy+VUJk0MGtQ/iKW0MzqKLMnTiqBBGBmbXTwX6qXEJUAoXSCym556WqAxkWqDrbp3Dp8p9SjHE3DsjXh5Y5nXjd82cdPD40S6YpBR4lvyhz+DZhYHhyMEN0PwkDRejfAu+U3nKrdOBLttgs58sYaDislbaBkKwihAPacF35Y4vFj6lLe5tqrA0YYXSXHpwD80KYwNilIrniqnptgde8RWGkkOePmkv6f2iflw2R9wtu1D62Iihz+0s6yrQ5rWYx2aOpOE=
    - secure: bS6dIGF1RxyAxtMi/tuIefwBrYrqbNlIWMFrTMiXLO7SM87GGItgOBm257BqjL7gctn1rjyl0q8LOJIuyxCIPAbSo3vZFgQEdnCswGH7cP5TEcJZt1gZPjTkuF3PZvQ8Jgago7hrXPQO6deRfhZtrAgGxm6o7u7GFR+ZX03ni0btu/qvriK94XjjZ98D9g1iaTeMqAWL4ybhi65pBYUrq4fBw3pRIFEB82byy4wvA0v5h0OH10U+gX92RQS17d81l1qx7in/VY8Uegd4JE+dvBROCVmGrNdRP5mPquqN0ULFKBjn0VuUIGlz+A/h802r141oPD5lHU3DVlkH3tuLZaw5ObYGzTqSjV89ukRP9CPu1oQ36rcO7852gj1+9PzYKQzAcFQeiLJk+jk5hfo+NBftEiZaIDKK4BUi+MFc7WJDPRIELnxpjeUpJxO1JquLVc2XOsdwtsKARHVqOamXcydZuf0h1UYZSpCf6aHZWH5glbFf2xiFDw6pbQItR76xKcE4IetepvW3KEqwnOQn2InaXs1YPD/I5yTNEDC1LOl8bHNs1h/AuKQwB2Ocin8BHznxs338UBtrN/Mitrt3P2EdgB2CHBN79/3/su5+xjTBi21xWkH2QwPqzrEswQ4kSqe/AiAol+qDFe3NJaH86E/JD+M2/drcyeuKjiCKLlI=

before_install:
  - go get github.com/jteeuwen/go-bindata/...
  - go get github.com/stretchr/testify/assert
  - go get github.com/cihub/seelog
  - go get github.com/mattn/go-sqlite3
  - go get github.com/jessevdk/go-flags
  - go get github.com/go-sql-driver/mysql
  - go get github.com/lib/pq
  - go get github.com/0x6e6562/gosnow
  - echo $PKG_CONFIG_PATH
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - .travis/oracle-instantclient/download_instantclient.sh
  - .travis/oracle-instantclient/install_instantclient.sh
  - .travis/oracle-instantclient/download_instantclient_sdk.sh
  - .travis/oracle-instantclient/install_instantclient_sdk.sh
  - sudo find / -name "sdk"
  - sudo find / -name "oci.h"
  - sudo find / -name "libclntsh.*"
  - sudo find / -name "libocci.*"
  - sudo find / -name "libociei.*"
  - sudo find / -name "libnnz11.*"
  - sudo find / -name "client64"
  - sudo find / -name "include"
  - export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
  - export LD_RUN_PATH=/usr/lib/oracle/12.1/client64/lib
  - go get github.com/mattn/go-oci8
  - export PATH=$HOME/gopath/bin:$PATH
  - mysql -e "CREATE DATABASE sqlc;"
  - mysql -e "CREATE USER 'sqlc'@'%' IDENTIFIED BY 'sqlc';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'sqlc'@'%' WITH GRANT OPTION;" -uroot
  - createuser sqlc
  - createdb sqlc -O sqlc
